spring:
  datasource:
    username: postgres
    password: zhassurbek
    url: jdbc:postgresql://localhost:5432/mix_spring

  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update


  # Security
  security:
    user:
      name: admininstrator
      password: password

server:
  port: 8090


token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

springdoc:
  api-docs:
    path: v3/api-docs