spring:
  datasource:
    username: postgres
    password: zhassurbek
    url: jdbc:postgresql://localhost:5432/mix_spring

  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update


  # Security
#  security:
#    user:
#      name: admin
#      password: passw@rd

server:
  port: 8090