spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/db_name

  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update


  # Security
#  security:
#    user:
#      name: admininstrator
#      password: password

server:
  port: 8090
