spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    listener:
#      simple:
#        retry:
#          enabled: true
#          initial-interval: 2s
#          max-interval: 20s
#          max-attempts: 5
#          multiplier: 2
