spring:
  datasource:
    username: postgres
    password: zhassurbek
    url: jdbc:postgresql://localhost:5432/mix_spring

  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update


  # Security
  security:
    user:
      name: admininstrator
      password: password

server:
  port: 8090


token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

springdoc:
  api-docs:
#    http://localhost:8080/v3/api-docs
    path: /v3/api-docs
#    customize the path of our API documentation by changing the springdoc.swagger-ui.path property inside our application.properties file
#  So now our API documentation will be available at http://localhost:8090/swagger-ui.html.
  swagger-ui:
    path: /swagger-ui.html

#  feign.okhttp.enabled=true
#
#  server.port=8085
#  spring.main.allow-bean-definition-overriding=true
#  logging.level.com.baeldung.cloud.openfeign.client=INFO
#  feign.hystrix.enabled=true
#
#  spring.cloud.openfeign.client.config.postClient.url=https://jsonplaceholder.typicode.com/posts/
#feign:
#  okhttp:
#    enabled:true
#feign:
#  okhttp:
#    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#hystrix:
#  metrics:
#    enabled: true